name: Build and Test

on:
  push:
   branches: [Dev]
  pull_request:
    branches: [Dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download repo
        uses: actions/checkout@v4

      - name: VS setup
        uses: microsoft/setup-msbuild@v2

      - name: C++ and Windows SDK
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Project
        run: msbuild "Initializing Direct3D.sln" /p:Configuration=Debug /p:Platform=x64
        shell: cmd

      - name: Unit test
        run: ctest --output-on-failure
        working-directory: ${{ github.workspace }}/x64/Debug
        shell: cmd

      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DX12-Build
          path: |
            ${{ github.workspace }}/x64/Debug
      
